#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# @author ENDERZOMBI102 <enderzombi102.end@gmail.com> 2024
# @description Quick and dirty `lint-openapi` config to better conform to the Prof's requests (and my preferences)
#
run:
  go: '1.17'
linters:
  enable:
    - 'errcheck'
    - 'gosimple'
    - 'govet'
    - 'ineffassign'
    - 'staticcheck'
    - 'unused'
    - 'bodyclose'
    - 'errname'
    - 'goconst'
    - 'gocritic'
    - 'prealloc'
    - 'rowserrcheck'
